---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-xorg-example
  labels:
    app: gke-xorg-example
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gke-xorg-example
  template:
    metadata:
      labels:
        app: gke-xorg-example
    spec:
      containers:
        - name: xorg
          image: "embarkstudios/xorg:latest"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            cpu: 100m
            memory: 128Mi
            nvidia.com/gpu: "1"
          env:
            - name: LD_LIBRARY_PATH
              value: "/usr/local/nvidia/lib64"
          args: [ "/bin/sleep", "infinity" ]
        - name: glxgears
          image: "embarkstudios/glxgears:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: DISPLAY
              value: ":0"
